### ISSUE TITLE
The shortcut doesn't work on the Ubuntu 18.04

### ISSUE THREAD

**Issue by martin-sun** [martyr-deepin/deepin-screenshot#36]
When I try to use Ctrl + Alt + A to quick run Deepin Screenshot, but it's doesn't work? how to configure the shortcut or customize the shortcut?

**Comment by tcstory** [comment]
do you add the short cut to run it?

**Comment by martin-sun** [comment]
How to add the short cut on Ubuntu 18.04?

**Comment by weeman1337** [comment]
You can add custom shortcuts in the keyboard settings.

**Comment by BLumia** [comment]
Not sure how your DE support custom shortcut but <kbd>Ctrl + Alt + A</kbd> is provided by Deepin Desktop Enviroment's daemon and is able to config via DDE's Control Center componment `dde-control-center`. 

So for other DE, you can manually add a shortcut in your DE's shortcut setting to simply execute `deepin-screenshot` :)
