### ISSUE TITLE
Wrong images folder in elementary OS

### ISSUE THREAD

**Issue by Gabriel-p** [martyr-deepin/deepin-screenshot#44]
According to [this app's wiki](https://wiki.deepin.org/index.php?title=Deepin_Screenshot&language=en#Save_Screenshot):

    * Select auto_save to save the image under the system default picture folder.

In elementary OS this saves the image to a `Desktop` folder instead the default `Images` folder.

**Comment by hualet** [comment]
Please check what your default Pictures folder is pointing at with:
```
xdg-user-dir PICTURES
```

**Comment by Gabriel-p** [comment]
It shows the correct path:

    /home/gabriel/Imágenes

**Comment by hualet** [comment]
Sorry, the wiki page must be outdated or mistaken, the correct one is 
```
Select autosave to auto save picture to the folder selected last time, the default directory is desktop at the first time.
```
I'll let someone correct the saying in the wiki, thanks.
