### ISSUE TITLE
Changing default location of screenshot save.

### ISSUE THREAD

**Issue by RitamChakraborty** [martyr-deepin/deepin-screenshot#45]
How to change the default location of screenshot save? I tried to change the settings in **dconf Editor** but didn't find any option. The screenshots are saved at _/home/user/Desktop_ by default but I want to change it to _/home/user/Pictures/Screenshots_.

**Comment by silviomm** [comment]
I'm using deepin-screenshot 4.1.8

- If you select the *specified folder* option, it will always open at the default picture folder *(probably ~/Pictures)*, since it uses `QStandardPaths::PicturesLocation`.
- If you select the *autosave*, he will save in the **last** *specified folder* option. 

So probably what you want is to save one time selecting */home/user/Pictures/Screenshots* as the specified folder, and then change mode to *autosave*, so that your next screenshots are saved automatically in your preference location

**Comment by BLumia** [comment]
Deepin-screenshot will remember the **last** save method (to Desktop / Clipboard / Specified folder / etc) you use, and it will also remember the save location you use. Additional, you can hold <kbd>Shift</kbd> when selecting a save method to avoid this behavior :)

**Comment by RitamChakraborty** [comment]
> I'm using deepin-screenshot 4.1.8
> 
> * If you select the _specified folder_ option, it will always open at the default picture folder _(probably ~/Pictures)_, since it uses `QStandardPaths::PicturesLocation`.
> * If you select the _autosave_, he will save in the **last** _specified folder_ option.
> 
> So probably what you want is to save one time selecting _/home/user/Pictures/Screenshots_ as the specified folder, and then change mode to _autosave_, so that your next screenshots are saved automatically in your preference location

I'm talking about taking screenshots with *Print Screen* button in the keyboard.

**Comment by BLumia** [comment]
> I'm talking about taking screenshots with _Print Screen_ button in the keyboard.

Try launch deepin-screenshot from launcher (or by pressing <kbd>Ctrl+Alt+A</kbd> if you are using Deepin) and manually choose a save method with a specified folder, then the program will use that method to save your screenshot when next time you press <kbd>PrintScreent</kbd>.

**Comment by RitamChakraborty** [comment]
> > I'm talking about taking screenshots with _Print Screen_ button in the keyboard.
> 
> Try launch deepin-screenshot from launcher (or by pressing Ctrl+Alt+A if you are using Deepin) and manually choose a save method with a specified folder, then the program will use that method to save your screenshot when next time you press PrintScreent.

Thanks man that works like a charm
