### ISSUE TITLE
Screenshot not being saved when there is no Desktop folder

### ISSUE THREAD

**Issue by burakcoskun** [martyr-deepin/deepin-screenshot#54]
To reproduce `mv Desktop` to somewhere else and try to save screenshot with deepin with default options. Some linux distros like arch doesn't come with a Desktop folder.

**Comment by BLumia** [comment]
What's the result if you run `xdg-user-dir DESKTOP` from terminal?

If the result is a path which is not existed, try run `xdg-user-dirs-update` or manually create the path?

**Comment by burakcoskun** [comment]
Currently I don't have access to my machine, but if I manually create Desktop folder it works. 

Not a big issue but shouldn't tool create the path if it doesn't exist?

**Comment by BLumia** [comment]
> Not a big issue but shouldn't tool create the path if it doesn't exist?

Yep, I did a PR(#55) about this, but I want to make sure your `xdg-user-dir` configuration is correct :)

**Comment by burakcoskun** [comment]
Perfect. Sure then I will check  my `xdg-user-dir` :). 

Thanks
