### ISSUE TITLE
can not qmake 

### ISSUE THREAD

**Issue by Matrixsun** [martyr-deepin/deepin-screenshot#56]
hello everyone 

my system is ubuntu 18.04 
when I run " qmake ..",  I get a error:
**Cannot read /${path_to}/deepin-screen: file to open is a directory
Error processing project file: ..**
how can I slove it

**Comment by BLumia** [comment]
Whoops, the README is outdated, we currently use CMake so you need:

``` bash
cd /path/to/the/source/
mkdir build
cd build
cmake ../         # instead of qmake
make
```

edit: I updated the README, it's up to date now.
