### ISSUE TITLE
Not working in Ubuntu 19.04

### ISSUE THREAD

**Issue by neumartin** [martyr-deepin/deepin-screenshot#57]
Hi!
I get this error when try to execute deepin-screenshot

> qt.qpa.plugin: Could not load the Qt platform plugin "dxcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: dxcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
> 
> Aborted (core dumped)

**Comment by filipehdbr** [comment]
Same here

**Comment by weeman1337** [comment]
I started it with the QT debug flag and got this stack trace:

```
Got keys from plugin meta data ("xcb")
Cannot load library /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libdxcb.so: (/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libdxcb.so: undefined symbol: _ZN22deepin_platform_plugin15WindowEventHook11windowEventEP6QEvent)
QLibraryPrivate::loadPlugin failed on "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libdxcb.so" : "Cannot load library /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libdxcb.so: (/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libdxcb.so: undefined symbol: _ZN22deepin_platform_plugin15WindowEventHook11windowEventEP6QEvent)"

```

**Comment by BLumia** [comment]
Which version is your `qt5dxcb-plugin` ?

cc: @zccrs

**Comment by neumartin** [comment]
> Which version is your `qt5dxcb-plugin` ?
> 
> cc: @zccrs

Hi!,

Is 1.1.22-1ubuntu1

**Comment by weeman1337** [comment]
Same here

**Comment by Jcs1994** [comment]
Same problem

**Comment by RaphaelAnjos27** [comment]
Same problem :/

**Comment by RaphaelAnjos27** [comment]
this with all the Deepin applications

**Comment by seven-steven** [comment]
same

**Comment by BLumia** [comment]
Are you guys using wayland instead of x11?

**Comment by neumartin** [comment]
x11, the default for Ubuntu.
Thanks!

**Comment by raiyan-hosn** [comment]
I am also facing same problem here.

**Comment by yunxi177** [comment]
same

**Comment by justforlxz** [comment]
The current version is 1.1.27, and ubuntu may need to have the maintainer update the package.

**Comment by Jcs1994** [comment]
The issues is fixed for me 

I did nothing but apt-get update  and apt-get upgrade
